name: Generate dotnet REST API
on:
  push:
    branches:
      - main
jobs:
  generate-template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      
      - name: Generate template
        run: dotnet new webapi -o rest
      
#      - name: Remove initialization workflow
#        run: rm .github/workflows/init_repository.yml
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit_message: Generate initial dotnet REST API
          delete-branch: true
